url: https://EWHA-CHAIN.github.io
baseurl: /

# Site settings
title: EWHA-CHAIN
email: ewha.chain@gmail.com
description: "Ewha Womans University Blockchain Society"


# Team names, titles and social links
people:
- name: a
  pic: 1
  position: 학회장
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: b
  pic: 2
  position: 총무
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: c
  pic: 3
  position: 재무
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket 
    url: http://bitbucket.org
  - title: github
    url: http://github.com/EWHA-CHAIN

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty